## unit tests use internal data stored in R/create_domino.R

test_that(
  "select_cluster_tf: identify differntial feature scores by one-sided wilcox test", {
    set.seed(123)
    cell_ids <- paste("cell", seq(300), sep = "_")
    clusters_tiny <- factor(
      c(rep("A", 100), rep("B", 100), rep("C", 100))
    )
    names(clusters_tiny) <- cell_ids
    # there are 5 TF features
    # feature scores are between 0 and 1, generated by a poisson distribution
    # TF1 is associated with cluster A
    # TF2 is associated with cluster B
    # TF3 is associated with cluster C
    # TF4 has even elevated scores across clusters
    # TF5 has 0 score across clusters
    
    simulate_poisson <- function(n, betaA, betaB, betaC) {
      id <- seq_along(3*n)
      cluster <- c(rep("A", n), rep("B", n), rep("C", n))
      E <- t(matrix(
        c(
          rep(c(1, 0, 0), n), # effect of cluster A
          rep(c(0, 1, 0), n), # effect of cluster B
          rep(c(0, 0, 1), n) # effect of cluster C
        ), 
        nrow = 3, ncol = 3 * n))
      mu <- exp(0 + betaA * E[,1] +  betaB * E[,2] +  betaC * E[,3])
      Y <- rpois(n = 3 * n, lambda = mu)
      # scale Y between values of 0 and 1
      Y_scale <- ((Y - min(Y)) / max(Y))
      df <- data.frame(
        "id" = id,
        "cluster" = cluster,
        "Y" = Y,
        "Y_scale" = Y_scale
      )
      return(df)
    }
    
    TF1 <- simulate_poisson(n = 100, betaA = 5, betaB = 1, betaC = 1)[["Y_scale"]]
    TF2 <- simulate_poisson(n = 100, betaA = 1, betaB = 5, betaC = 1)[["Y_scale"]]
    TF3 <- simulate_poisson(n = 100, betaA = 1, betaB = 1, betaC = 5)[["Y_scale"]]
    TF4 <- simulate_poisson(n = 100, betaA = 3, betaB = 3, betaC = 3)[["Y_scale"]]
    TF5 <- simulate_poisson(n = 100, betaA = 0, betaB = 0, betaC = 0)[["Y_scale"]]
    
    features_tiny <- t(matrix(
      c(TF1, TF2, TF3, TF4, TF5),
      ncol = 5, nrow = 300, 
      dimnames = list(
        cell_ids, 
        c("TF1", "TF2", "TF3", "TF4", "TF5")
      )
    ))
    
    tf_pval_mat <- select_cluster_tf(
      features = features_tiny, clusters = clusters_tiny, 
      verbose = FALSE, method = "one.sided.wilcox"
    )
    expect_true(tf_pval_mat["TF1", "A"] < 0.05)
    expect_true(tf_pval_mat["TF2", "B"] < 0.05)
    expect_true(tf_pval_mat["TF3", "C"] < 0.05)
    expect_true(sum(tf_pval_mat["TF4",] < 0.05) == 0) 
    expect_true(sum(tf_pval_mat["TF5",] < 0.05) == 0)
  }
)

